# `dependabot.yml` file with updates

# Update manually "Insights -> Dependency Graph -> Dependabot"

version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/scripts/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 0

  # Configuration for pyproj
  - package-ecosystem: "pip"
    directory: "/scripts/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 1

  # GitHub actions themselves
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
